[build-system]
requires = ["wheel", "setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length     = 120
target-version  = ["py38"]
include         = ".*pyi?$"

[tool.coverage.run]
concurrency = ["multiprocessing"]
parallel = true
branch = true
timid = false
source = ["yuyo"]

[tool.coverage.report]
precision = 2
show_missing = true
skip_covered = false
exclude_lines = [
    "^\\s*\\.\\.\\.$",
    "^\\s*@abc.abstractmethod$",
    "^if typing.TYPE_CHECKING:$"
]

[tool.isort]
profile = "black"
force_single_line = true

[tool.pyright]
include = ["yuyo", "noxfile.py"]

pythonVersion = "3.8"
reportCallInDefaultInitializer = "none"
reportImplicitStringConcatenation = "none"
reportMissingImports = "error"
reportMissingModuleSource = "error"
reportMissingTypeStubs = "error"
reportUnusedCallResult = "none"

reportUninitializedInstanceVariable = "warning" # Seems to lead to false-posities when inheriance and
                                                # _ properties are involved
reportIncompatibleMethodOverride = "warning"    # This relies on ordering for key-word only arguments 
                                                # which is more annoying than it's worth
reportUnknownMemberType = "warning"             # This messes with instance checking generic objects
reportUnknownArgumentType = "warning"           # Pretty much the same as reportUnknownMemberType
reportImportCycles = "warning"                  # This isn't necessarily an issue if it's type checking only.

[tool.pytest.ini_options]
# import-mode = "???"
testpaths = ["tests"]
required_plugins = ["pytest-asyncio"]
