name: Update license

on:
  schedule:
    - cron: "0 7 * 1 0"
  workflow_dispatch:

jobs:
  update-license:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r ./piped/python/base-requirements/nox.txt

      - name: Update license
        run: python -m nox -s update-license

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          author: "always-on-duty[bot] <120557446+always-on-duty[bot]@users.noreply.github.com>"
          branch: task/upgrade-deps
          commit-message: Upgrade dependency locks
          committer: "always-on-duty[bot] <120557446+always-on-duty[bot]@users.noreply.github.com>"
          title: Upgrade dependency locks
          token: ${{ secrets.ACTIONS_TOKEN || secrets.GITHUB_TOKEN }}
